import * as stylex from "@stylexjs/stylex";

export const typography = stylex.create({
	blockquote: {
		borderInlineStartWidth: 3,
		borderInlineStartStyle: "solid",
		borderInlineStartColor: "var(--accent)",
		color: "var(--text-2)",
		fontStyle: "italic",
		marginBlock: "1.5rem",
		paddingInlineStart: "1rem",
	},
	code: {
		backgroundColor: "var(--bg-elevated)",
		borderRadius: 4,
		fontFamily: "var(--font-mono)",
		fontSize: "0.9em",
		paddingBlock: "0.125rem",
		paddingInline: "0.375rem",
	},
	container: {
		color: "var(--text-1)",
		fontFamily: "var(--font-sans)",
		fontSize: "1rem",
		lineHeight: 1.7,
		maxWidth: "65ch",
	},
	h1: {
		fontFamily: "var(--font-display)",
		fontSize: "clamp(2.25rem, 6vw, 4rem)",
		fontWeight: 800,
		letterSpacing: "-0.035em",
		lineHeight: 1.1,
		marginBlock: 0,
	},
	h2: {
		fontFamily: "var(--font-display)",
		fontSize: "1.5rem",
		fontWeight: 700,
		lineHeight: 1.25,
		marginBlockStart: "2rem",
		marginBlockEnd: "0.75rem",
	},
	h3: {
		fontFamily: "var(--font-display)",
		fontSize: "1.25rem",
		fontWeight: 700,
		lineHeight: 1.3,
		marginBlockStart: "1.5rem",
		marginBlockEnd: "0.5rem",
	},
	img: { borderRadius: 6, height: "auto", maxWidth: "100%" },
	li: { marginBlockEnd: "0.5rem" },
	link: { color: "var(--accent-text)", textDecorationLine: "underline", textUnderlineOffset: "0.16em" },
	ol: { listStyleType: "decimal", marginBlock: "1rem", paddingInlineStart: "1.5rem" },
	p: { marginBlock: 0, marginBlockEnd: "1.25rem" },
	pre: {
		backgroundColor: "var(--bg-elevated)",
		borderRadius: 6,
		fontFamily: "var(--font-mono)",
		fontSize: "0.875rem",
		lineHeight: 1.6,
		marginBlock: "1.5rem",
		overflowX: "auto",
		padding: 8,
	},
	strong: { fontWeight: 700 },
	ul: { listStyleType: "disc", marginBlock: "1rem", paddingInlineStart: "1.5rem" },
});
