import * as stylex from "@stylexjs/stylex";

const colors = {
	border: "var(--border)",
	muted: "var(--text-2)",
	text: "var(--text-1)",
	accent: "var(--accent-text)",
	accentHover: "var(--accent)",
	card: "var(--bg-card)",
	elevated: "var(--bg-elevated)",
	white: "var(--btn-text)",
};

export const styles = stylex.create({
	aspectVideo: { aspectRatio: "16 / 9" },
	bgGray100: { backgroundColor: colors.elevated },
	bgGray800: { backgroundColor: "#1f2937" },
	border2: { borderWidth: 2, borderStyle: "solid" },
	borderGray200: { borderColor: colors.border },
	borderGray700: { borderColor: colors.border },
	borderOrange500: { borderColor: "#f97316" },
	borderOpacity60: { borderColor: "color-mix(in oklch, var(--border) 60%, transparent)" },
	borderT: { borderTopWidth: 1, borderTopStyle: "solid" },
	flex: { display: "flex" },
	flex1: { flex: 1 },
	flexCol: { flexDirection: "column" },
	flexWrap: { flexWrap: "wrap" },
	fontBold: { fontWeight: 700 },
	fontMedium: { fontWeight: 500 },
	fontSans: { fontFamily: "var(--font-sans)" },
	fontSemibold: { fontWeight: 600 },
	gap3: { gap: "0.75rem" },
	gap4: { gap: "1rem" },
	gap6: { gap: "1.5rem" },
	grid: { display: "grid" },
	gridCols1: { gridTemplateColumns: "repeat(1, minmax(0, 1fr))" },
	gridCols2: { gridTemplateColumns: "repeat(2, minmax(0, 1fr))" },
	gridCols3: { gridTemplateColumns: "repeat(3, minmax(0, 1fr))" },
	gridCols4: { gridTemplateColumns: "repeat(4, minmax(0, 1fr))" },
	gridCols2Sm: { gridTemplateColumns: { default: "repeat(1, minmax(0, 1fr))", "@media (min-width: 640px)": "repeat(2, minmax(0, 1fr))" } },
	gridCols3Sm: { gridTemplateColumns: { default: "repeat(1, minmax(0, 1fr))", "@media (min-width: 640px)": "repeat(3, minmax(0, 1fr))" } },
	gridCols2Md: { gridTemplateColumns: { default: "repeat(1, minmax(0, 1fr))", "@media (min-width: 768px)": "repeat(2, minmax(0, 1fr))" } },
	gridCols4Xl: { gridTemplateColumns: { default: "none", "@media (min-width: 1280px)": "repeat(4, minmax(0, 1fr))" } },
	grow: { flexGrow: 1 },
	hAuto: { height: "auto" },
	h36Md: { height: { default: null, "@media (min-width: 768px)": "9rem" } },
	h48Lg: { height: { default: null, "@media (min-width: 1024px)": "12rem" } },
	hFull: { height: "100%" },
	hidden: { display: "none" },
	inlineFlex: { display: "inline-flex" },
	itemsBaselineXl: { alignItems: { default: null, "@media (min-width: 1280px)": "baseline" } },
	itemsCenter: { alignItems: "center" },
	itemsStart: { alignItems: "flex-start" },
	leading6: { lineHeight: "1.5rem" },
	leading8: { lineHeight: "2rem" },
	leadingRelaxed: { lineHeight: 1.625 },
	minHScreen: { minHeight: "100vh" },
	maxW3xl: { maxWidth: "48rem" },
	maxWFull: { maxWidth: "100%" },
	maxWNone: { maxWidth: "none" },
	maxWLg: { maxWidth: "32rem" },
	maxWXl: { maxWidth: { default: "48rem", "@media (min-width: 1280px)": "64rem" } },
	mbAuto: { marginBottom: "auto" },
	mb05: { marginBottom: "0.125rem" },
	mb2: { marginBottom: "0.5rem" },
	mb3: { marginBottom: "0.75rem" },
	mb4: { marginBottom: "1rem" },
	mb5: { marginBottom: "1.25rem" },
	mb6: { marginBottom: "1.5rem" },
	mb12: { marginBottom: "3rem" },
	mdWHalf: { width: { default: "100%", "@media (min-width: 768px)": "50%" } },
	mr3: { marginRight: "0.75rem" },
	mt1: { marginTop: "0.25rem" },
	mtAuto: { marginTop: "auto" },
	mxAuto: { marginInline: "auto" },
	objectCenter: { objectPosition: "center" },
	objectCover: { objectFit: "cover" },
	overflowHidden: { overflow: "hidden" },
	p1_5: { padding: "0.375rem" },
	p4: { padding: "1rem" },
	p6: { padding: "1.5rem" },
	pt8: { paddingTop: "2rem" },
	px4: { paddingInline: "1rem" },
	px1_5: { paddingInline: "0.375rem" },
	px6Sm: { paddingInline: { default: "1rem", "@media (min-width: 640px)": "1.5rem" } },
	py05: { paddingBlock: "0.125rem" },
	py4: { paddingBlock: "1rem" },
	relative: { position: "relative" },
	rounded: { borderRadius: "0.25rem" },
	roundedMd: { borderRadius: "0.375rem" },
	roundedLg: { borderRadius: "0.5rem" },
	spaceY15: { display: "flex", flexDirection: "column", gap: "0.375rem" },
	spaceY2: { display: "flex", flexDirection: "column", gap: "0.5rem" },
	spaceY3: { display: "flex", flexDirection: "column", gap: "0.75rem" },
	spaceY4: { display: "flex", flexDirection: "column", gap: "1rem" },
	spaceY6: { display: "flex", flexDirection: "column", gap: "1.5rem" },
	spaceY12: { display: "flex", flexDirection: "column", gap: "3rem" },
	spaceY2Xl: { display: "flex", flexDirection: "column", gap: { default: "0.5rem", "@media (min-width: 1280px)": 0 } },
	srOnly: { position: "absolute", width: 1, height: 1, padding: 0, margin: -1, overflow: "hidden", clip: "rect(0, 0, 0, 0)", whiteSpace: "nowrap", borderWidth: 0 },
	textBase: { fontSize: "1rem" },
	textXs: { fontSize: "0.75rem", lineHeight: "1rem" },
	textSm: { fontSize: "0.875rem", lineHeight: "1.25rem" },
	textLg: { fontSize: "1.125rem", lineHeight: "1.75rem" },
	textXl: { fontSize: "1.25rem", lineHeight: "1.75rem" },
	text2xl: { fontSize: "1.5rem", lineHeight: "2rem" },
	textCenter: { textAlign: "center" },
	textGray400: { color: colors.muted },
	textGray500: { color: colors.muted },
	textGray900: { color: colors.text },
	textPrimary500: { color: colors.accent },
	textPrimary100: { color: "var(--accent-dim)" },
	textWhite: { color: colors.white },
	darkTextPrimary100: { color: colors.accent },
	darkTextWhite: { color: colors.text },
	textYellow500: { color: "#eab308" },
	trackingTight: { letterSpacing: "-0.025em" },
	uppercase: { textTransform: "uppercase" },
	wFull: { width: "100%" },
	xlPx0: { paddingInline: { default: "1rem", "@media (min-width: 1280px)": 0 } },
	colSpan3Xl: { gridColumn: { default: null, "@media (min-width: 1280px)": "span 3 / span 3" } },
	mdGridCols2: { gridTemplateColumns: { default: "repeat(1, minmax(0, 1fr))", "@media (min-width: 768px)": "repeat(2, minmax(0, 1fr))" } },
	mdGridCols2Only: { display: { default: "block", "@media (min-width: 768px)": "grid" }, gridTemplateColumns: { default: "none", "@media (min-width: 768px)": "repeat(2, minmax(0, 1fr))" } },
	smGridCols2: { gridTemplateColumns: { default: "repeat(1, minmax(0, 1fr))", "@media (min-width: 640px)": "repeat(2, minmax(0, 1fr))" } },
	smGridCols3: { gridTemplateColumns: { default: "repeat(1, minmax(0, 1fr))", "@media (min-width: 640px)": "repeat(3, minmax(0, 1fr))" } },
	xlGrid: { display: { default: null, "@media (min-width: 1280px)": "grid" } },
	xlSpaceY0: { gap: { default: null, "@media (min-width: 1280px)": 0 } },
	hoverUnderline: { textDecorationLine: { default: null, ":hover": "underline" } },
	hoverTextGray700: { color: { default: null, ":hover": colors.text } },
	hoverTextGray200: { color: { default: null, ":hover": colors.white } },
	hoverTextPrimary600: { color: { default: null, ":hover": colors.accentHover } },
});

export const sx = (...tokens: unknown[]) => stylex.attrs(tokens as never[]);
